import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import { useRouter } from 'next/router'
import VoteButton from '../../Components/VoteButton'
import { useState } from 'react'
export default function Home() {
    const router = useRouter()
    const { id } = router.query
    const [disabled, setDisabled] = useState(false)
    
    const HandleVote = (optionId) =>{
        fetch('/api/option/vote/' + optionId,
        {
            method: "POST",
            body: JSON.stringify({data: optionId})
        })


    }
    const HandleClick =  (e) =>{
        e.preventDefault()
        
        const voteData = e.target.value
        HandleVote(voteData)
        setDisabled(true)
    
      }

    return (
        <div className={styles.container}>
            <Head>
                <title>Donkpoll</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div className={styles.grid}>
                    <h1 className={styles.title}>
                        Question number: {id}
                    </h1>
                    <VoteButton value={1} prompt={"Option 1"} clickInstruction={HandleClick} disabled={disabled}/>
                    <VoteButton value={2} prompt={"Option 2"} clickInstruction={HandleClick} disabled={disabled}/>
                    <VoteButton value={3} prompt={"Option 3"} clickInstruction={HandleClick} disabled={disabled}/>
                    <VoteButton value={4} prompt={"Option 4"} clickInstruction={HandleClick} disabled={disabled}/>
                    

                </div>


            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    )
}
