import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import QuestionForm from '../Components/QuestionForm'
/* 
 
  possibly refactor the create question fetch cascade using prisma create many with a nested write, (see comments in QuestionForm)
  TODO: next SWR can provide real time data fetching and cache invalidation stuff, use that instead of an interval possibly? 
  ^ https://swr.vercel.app/docs/getting-started
*/
export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Donkpoll</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
       
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <QuestionForm />
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>


          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
