import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import QuestionForm from '../Components/QuestionForm'
import Link from 'next/link'
/* 
 
  possibly refactor the create question fetch cascade using prisma create many with a nested write, (see comments in QuestionForm)
  TODO: next SWR can provide real time data fetching and cache invalidation stuff, use that instead of an interval possibly? 
  ^ https://swr.vercel.app/docs/getting-started
*/
export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Donkpoll</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="h-screen  w-full flex flex-col items-center justify-center">

          <h1 className='text-2xl'>
            Settle a Question
          </h1>

          <QuestionForm />
        </div>
      </main>

      <footer className={styles.footer}>
        <Link href={"/"}>Return Home</Link>
      </footer>
    </div>
  )
}
